### ISSUE TITLE
New addition to the list

### ISSUE THREAD

**Issue by motss** [olivewind/awesome-deno#7]
I made a `deno` version of one of my NPM packages.

Please consider adding this new package [normalize-diacritics][nd-url] for `deno`. TA.

[nd-url]: https://github.com/motss/normalize-diacritics/tree/deno

**Comment by olivewind** [comment]
@motss  sounds good, please create a pull request , i will merge it

**Comment by motss** [comment]
Done!

**Comment by motss** [comment]
Closed at https://github.com/denolib/awesome-deno/pull/16
